handle multiple quotes

diff --git a/bin/loot b/bin/loot
--- a/bin/loot
+++ b/bin/loot
@@ -1,16 +1,25 @@
 #!/usr/bin/env sh
+set -e
+
+loot() {
+  QUOTE_FILE="$1"
+  if test -r "$QUOTE_FILE"; then
+    (echo "0"; cat "$QUOTE_FILE" | grep -n '^%$' | cut -f1 -d:) | sed ':begin;$!N;s/^\(.*\)\n\(.*\)/NR>\1\&\&NR<\2/g' | shuf -n 1 | xargs -I{} awk 'END{print ""}'{} "$QUOTE_FILE" | fold -sw 80
+  else
+    echo "Error: Quote file is not readable. ($QUOTE_FILE)"
+    exit 1
+  fi
+}
+
 
 if test -d "$1"; then
-  QUOTE_FILE="$(find "$1" -type f -print0 | shuf -zn 1 | tr -d '\0')"
+  for RANDOM_FILE in $(find "$1" -type f | shuf -rn 3); do
+    loot "$RANDOM_FILE"
+  done
 else
-  QUOTE_FILE="$1"
-fi
-
-if test -r "$QUOTE_FILE"; then
-  (echo "0"; cat "$QUOTE_FILE" | grep -n '^%$' | cut -f1 -d:) | sed ':begin;$!N;s/^\(.*\)\n\(.*\)/NR>\1\&\&NR<\2/g' | shuf -n 1 | xargs -I{} awk 'END{print ""}'{} "$QUOTE_FILE" | fold -sw 80
-else
-  echo "Error: Quote file is not readable. ($QUOTE_FILE)"
-  exit 1
+  for SINGLE_FILE in $(echo "$1" | shuf -rn 3); do
+    loot "$SINGLE_FILE"
+  done
 fi
 
 exit 0
